services:
  redis:
    image: redis:7.2
    container_name: redis-server
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  redis-data:
  mongo-data:
