services:
  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: always

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    restart: unless-stopped

volumes:
  redis-data:
  mongo-data:
