# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: command.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'command.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcommand.proto\x12\x08terminal\"K\n\x0e\x43omandoRequest\x12\x0f\n\x07\x63omando\x18\x01 \x01(\t\x12\x12\n\nargumentos\x18\x02 \x03(\t\x12\x14\n\x0chash_cliente\x18\x03 \x01(\t\"D\n\x0f\x43omandoResponse\x12\r\n\x05saida\x18\x01 \x03(\t\x12\x0c\n\x04\x65rro\x18\x02 \x01(\t\x12\x14\n\x0c\x63odigo_saida\x18\x03 \x01(\x05\x32Y\n\x0fTerminalService\x12\x46\n\x0f\x45xecutarComando\x12\x18.terminal.ComandoRequest\x1a\x19.terminal.ComandoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'command_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMANDOREQUEST']._serialized_start=27
  _globals['_COMANDOREQUEST']._serialized_end=102
  _globals['_COMANDORESPONSE']._serialized_start=104
  _globals['_COMANDORESPONSE']._serialized_end=172
  _globals['_TERMINALSERVICE']._serialized_start=174
  _globals['_TERMINALSERVICE']._serialized_end=263
# @@protoc_insertion_point(module_scope)
