# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import command_pb2 as command__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in command_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TerminalServiceStub(object):
    """Serviço de terminal com envio e resposta de comandos
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecutarComando = channel.unary_unary(
                '/terminal.TerminalService/ExecutarComando',
                request_serializer=command__pb2.ComandoRequest.SerializeToString,
                response_deserializer=command__pb2.ComandoResponse.FromString,
                _registered_method=True)


class TerminalServiceServicer(object):
    """Serviço de terminal com envio e resposta de comandos
    """

    def ExecutarComando(self, request, context):
        """Envia um comando com argumentos e recebe a saída
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TerminalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecutarComando': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutarComando,
                    request_deserializer=command__pb2.ComandoRequest.FromString,
                    response_serializer=command__pb2.ComandoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'terminal.TerminalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('terminal.TerminalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TerminalService(object):
    """Serviço de terminal com envio e resposta de comandos
    """

    @staticmethod
    def ExecutarComando(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terminal.TerminalService/ExecutarComando',
            command__pb2.ComandoRequest.SerializeToString,
            command__pb2.ComandoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
