// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: command.proto

#include "command.pb.h"
#include "command.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace terminal {

static const char* TerminalService_method_names[] = {
  "/terminal.TerminalService/ExecutarComando",
};

std::unique_ptr< TerminalService::Stub> TerminalService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TerminalService::Stub> stub(new TerminalService::Stub(channel, options));
  return stub;
}

TerminalService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ExecutarComando_(TerminalService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TerminalService::Stub::ExecutarComando(::grpc::ClientContext* context, const ::terminal::ComandoRequest& request, ::terminal::ComandoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::terminal::ComandoRequest, ::terminal::ComandoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExecutarComando_, context, request, response);
}

void TerminalService::Stub::async::ExecutarComando(::grpc::ClientContext* context, const ::terminal::ComandoRequest* request, ::terminal::ComandoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::terminal::ComandoRequest, ::terminal::ComandoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecutarComando_, context, request, response, std::move(f));
}

void TerminalService::Stub::async::ExecutarComando(::grpc::ClientContext* context, const ::terminal::ComandoRequest* request, ::terminal::ComandoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecutarComando_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::terminal::ComandoResponse>* TerminalService::Stub::PrepareAsyncExecutarComandoRaw(::grpc::ClientContext* context, const ::terminal::ComandoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::terminal::ComandoResponse, ::terminal::ComandoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExecutarComando_, context, request);
}

::grpc::ClientAsyncResponseReader< ::terminal::ComandoResponse>* TerminalService::Stub::AsyncExecutarComandoRaw(::grpc::ClientContext* context, const ::terminal::ComandoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecutarComandoRaw(context, request, cq);
  result->StartCall();
  return result;
}

TerminalService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TerminalService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TerminalService::Service, ::terminal::ComandoRequest, ::terminal::ComandoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](TerminalService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::terminal::ComandoRequest* req,
             ::terminal::ComandoResponse* resp) {
               return service->ExecutarComando(ctx, req, resp);
             }, this)));
}

TerminalService::Service::~Service() {
}

::grpc::Status TerminalService::Service::ExecutarComando(::grpc::ServerContext* context, const ::terminal::ComandoRequest* request, ::terminal::ComandoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace terminal

