// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: command.proto
#ifndef GRPC_command_2eproto__INCLUDED
#define GRPC_command_2eproto__INCLUDED

#include "command.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace terminal {

// Serviço de terminal com envio e resposta de comandos
class TerminalService final {
 public:
  static constexpr char const* service_full_name() {
    return "terminal.TerminalService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Envia um comando com argumentos e recebe a saída
    virtual ::grpc::Status ExecutarComando(::grpc::ClientContext* context, const ::terminal::ComandoRequest& request, ::terminal::ComandoResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal::ComandoResponse>> AsyncExecutarComando(::grpc::ClientContext* context, const ::terminal::ComandoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal::ComandoResponse>>(AsyncExecutarComandoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal::ComandoResponse>> PrepareAsyncExecutarComando(::grpc::ClientContext* context, const ::terminal::ComandoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::terminal::ComandoResponse>>(PrepareAsyncExecutarComandoRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Envia um comando com argumentos e recebe a saída
      virtual void ExecutarComando(::grpc::ClientContext* context, const ::terminal::ComandoRequest* request, ::terminal::ComandoResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ExecutarComando(::grpc::ClientContext* context, const ::terminal::ComandoRequest* request, ::terminal::ComandoResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::terminal::ComandoResponse>* AsyncExecutarComandoRaw(::grpc::ClientContext* context, const ::terminal::ComandoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::terminal::ComandoResponse>* PrepareAsyncExecutarComandoRaw(::grpc::ClientContext* context, const ::terminal::ComandoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ExecutarComando(::grpc::ClientContext* context, const ::terminal::ComandoRequest& request, ::terminal::ComandoResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal::ComandoResponse>> AsyncExecutarComando(::grpc::ClientContext* context, const ::terminal::ComandoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal::ComandoResponse>>(AsyncExecutarComandoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal::ComandoResponse>> PrepareAsyncExecutarComando(::grpc::ClientContext* context, const ::terminal::ComandoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::terminal::ComandoResponse>>(PrepareAsyncExecutarComandoRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ExecutarComando(::grpc::ClientContext* context, const ::terminal::ComandoRequest* request, ::terminal::ComandoResponse* response, std::function<void(::grpc::Status)>) override;
      void ExecutarComando(::grpc::ClientContext* context, const ::terminal::ComandoRequest* request, ::terminal::ComandoResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::terminal::ComandoResponse>* AsyncExecutarComandoRaw(::grpc::ClientContext* context, const ::terminal::ComandoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::terminal::ComandoResponse>* PrepareAsyncExecutarComandoRaw(::grpc::ClientContext* context, const ::terminal::ComandoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ExecutarComando_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Envia um comando com argumentos e recebe a saída
    virtual ::grpc::Status ExecutarComando(::grpc::ServerContext* context, const ::terminal::ComandoRequest* request, ::terminal::ComandoResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ExecutarComando : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ExecutarComando() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ExecutarComando() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecutarComando(::grpc::ServerContext* /*context*/, const ::terminal::ComandoRequest* /*request*/, ::terminal::ComandoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecutarComando(::grpc::ServerContext* context, ::terminal::ComandoRequest* request, ::grpc::ServerAsyncResponseWriter< ::terminal::ComandoResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ExecutarComando<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ExecutarComando : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ExecutarComando() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::terminal::ComandoRequest, ::terminal::ComandoResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::terminal::ComandoRequest* request, ::terminal::ComandoResponse* response) { return this->ExecutarComando(context, request, response); }));}
    void SetMessageAllocatorFor_ExecutarComando(
        ::grpc::MessageAllocator< ::terminal::ComandoRequest, ::terminal::ComandoResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::terminal::ComandoRequest, ::terminal::ComandoResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ExecutarComando() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecutarComando(::grpc::ServerContext* /*context*/, const ::terminal::ComandoRequest* /*request*/, ::terminal::ComandoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExecutarComando(
      ::grpc::CallbackServerContext* /*context*/, const ::terminal::ComandoRequest* /*request*/, ::terminal::ComandoResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ExecutarComando<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ExecutarComando : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ExecutarComando() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ExecutarComando() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecutarComando(::grpc::ServerContext* /*context*/, const ::terminal::ComandoRequest* /*request*/, ::terminal::ComandoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ExecutarComando : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ExecutarComando() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ExecutarComando() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecutarComando(::grpc::ServerContext* /*context*/, const ::terminal::ComandoRequest* /*request*/, ::terminal::ComandoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecutarComando(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ExecutarComando : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ExecutarComando() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ExecutarComando(context, request, response); }));
    }
    ~WithRawCallbackMethod_ExecutarComando() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecutarComando(::grpc::ServerContext* /*context*/, const ::terminal::ComandoRequest* /*request*/, ::terminal::ComandoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ExecutarComando(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ExecutarComando : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ExecutarComando() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::terminal::ComandoRequest, ::terminal::ComandoResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::terminal::ComandoRequest, ::terminal::ComandoResponse>* streamer) {
                       return this->StreamedExecutarComando(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ExecutarComando() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ExecutarComando(::grpc::ServerContext* /*context*/, const ::terminal::ComandoRequest* /*request*/, ::terminal::ComandoResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedExecutarComando(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::terminal::ComandoRequest,::terminal::ComandoResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ExecutarComando<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ExecutarComando<Service > StreamedService;
};

}  // namespace terminal


#endif  // GRPC_command_2eproto__INCLUDED
